package com.ethor.testbed.api.test.report;

public enum TestModule {

	AUTHENTICATION,
	CHAIN,
	RESTAURANT,
	RESTAURANT_FILTER,
	CATEGORY,
	SPECIAL,
	SPECIAL_FILTER,
	MENUITEM,
	MENUITEM_FILTER,
	CUSTOMER_BY_PHONE,
	CUSTOMER_BY_EMAIL,
	ORDER,
	CHAIN_COUNT,
	RESTAURANT_COUNT,
	CATEGORY_COUNT,
	SPECIAL_COUNT,
	MENUITEM_COUNT,
	CHAIN_BYID,
	RESTAURANT_BYID,
	CATEGORY_BYID,
	MENUITEM_BYID
}
